name: math
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - biopython
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - python==3.11.9
  - PyWavelets
  - scikit-learn
  - scipy
  - seaborn
